name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
  release:
    types: [published]

env:
  PROJECT_TYPE: KEXT

jobs:
  build:
    name: Build
    runs-on: macos-latest
    env:
      JOB_TYPE: BUILD
    steps:
      - uses: actions/checkout@v4.1.7
        with:
          repository: acidanthera/MacKernelSDK
          path: MacKernelSDK
      - name: CI Bootstrap
        run: |
          src=$(/usr/bin/curl -Lfs https://raw.githubusercontent.com/acidanthera/ocbuild/master/ci-bootstrap.sh) && eval "$src" || exit 1
      - name: Lilu Bootstrap
        run: |
          src=$(/usr/bin/curl -Lfs https://raw.githubusercontent.com/acidanthera/Lilu/master/Lilu/Scripts/bootstrap.sh) && eval "$src" || exit 1
      - run: xcodebuild -project "GenericCardReaderFriend.xcodeproj" -scheme "GenericCardReaderFriend" -derivedDataPath build clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -jobs 1 -configuration Debug
      - run: xcodebuild -project "GenericCardReaderFriend.xcodeproj" -scheme "GenericCardReaderFriend" -derivedDataPath build clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -jobs 1 -configuration Release

      - name: Upload to Artifacts
        uses: actions/upload-artifact@v4.3.4
        with:
          name: Artifacts
          path: build/*/*.zip

      - name: Upload to Artifacts
        uses: actions/upload-artifact@v4.3.4
        with:
          name: Artifacts
          path: build/*/*.zip
